### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by rugk** [tmate-io/tmate-ssh-server#41]
I know it's common jargon, but I still think the term "slave" should not be used and is not appropriate.

See https://en.wikipedia.org/wiki/Master/slave_(technology)#Terminology_concerns for details and how other (big) companies do it/name their products.

**Comment by nviennot** [comment]
It should be renamed to "replica", I haven't had time to do it

**Comment by grzm** [comment]
Why not server? That's the language used elsewhere in the README:

```
tmate server side

tmate-slave is the server side part of tmate.io.
```

Seems `tmate-server` would be a natural choice.

**Comment by varac** [comment]
I also like `tmate-server` the most.

**Comment by ChristophBerg** [comment]
I'd also suggest renaming it to `tmate-server`. Afaict there's nothing slave-ish in the way it works, both tmate instances and plain ssh clients connect to it, so "server" seems just fine. 

We are pondering uploading this to Debian, and we'd better get the name right before that.

**Comment by nviennot** [comment]
I agree. I'm going to change the name this week.

This month, I'm going to spend time on renaming all the projects and making docker images. The infrastructure needs a rehaul.

Because tmux has a server/client architecture already, it might be confusing to reuse the name "server". (both the tmate-server and tmate-client have runs a tmux server).

On the design architecture diagram, I ended up renaming tmate-slave to "replica":

![image](https://user-images.githubusercontent.com/297060/55800071-d79a6d80-5aa0-11e9-8b20-c9fa25eca003.png)

Does tmate-replica make sense?, or we should stick to tmate-server?

**Comment by ChristophBerg** [comment]
I'd say "server" and "replica" only make sense from a tmux perspective (the contents of terminal on the server host are replicated to the replica host). When looking at the whole setup from an end user perspective, the thing running on the target host is a client that connects to a server running elsewhere in the internet.

**Comment by nviennot** [comment]
I think the name `tmate-ssh-server` makes sense from both a user perspective, and an architecture perspective.
